version: '3'

services:
  app_manager:
    build: fastFoodManager
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: mysql://root:JjNlCZhrkTiRxXkXAIxmjTSpFvLquIpi@junction.proxy.rlwy.net:39909/railway
      DB_USER_NAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      foodManager:
          condition: service_healthy
  foodManager:
    image: mysql:8.0.27 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: railway
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10