name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      DB_URL: jdbc:mysql://root:JjNlCZhrkTiRxXkXAIxmjTSpFvLquIpi@junction.proxy.rlwy.net:39909/railway
      DB_USER_NAME: root
      DB_PASSWORD: JjNlCZhrkTiRxXkXAIxmjTSpFvLquIpi
      SPRING_PROFILES_ACTIVE: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Check database connection
        run: |
          echo "Checking database connection..."
          until nc -z junction.proxy.rlwy.net 39909; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t jorgeovm/fastfoodmanager  .

      - name: Push Docker image
        run: docker push jorgeovm/fastfoodmanager
